# Generated by Django 5.1.4 on 2025-02-05 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Totalsolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('service', 'Service'), ('all', 'All Categories')], default='all', max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('specification', models.TextField(blank=True, max_length=250, null=True)),
                ('uom', models.CharField(max_length=300)),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Buying price must be non-negative.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation_received_month', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('list_price', models.DecimalField(decimal_places=2, default=0.0, help_text='List price must be non-negative.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.FloatField(default=0.0, help_text='Discount as a percentage (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sales_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Sales price must be non-negative.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sales_margin', models.DecimalField(decimal_places=2, default=0.0, help_text='Sales margin must be non-negative.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
