# Generated by Django 5.1.4 on 2025-03-25 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalsolutions',
            name='sales_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sales margin as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
