# Generated by Django 5.1.4 on 2025-03-26 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0003_alter_totalsolutions_sales_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalsolutions',
            name='buying_price',
            field=models.IntegerField(default=0, help_text='Buying price must be non-negative.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount as a percentage (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='list_price',
            field=models.IntegerField(default=0, help_text='List price must be non-negative.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='sales_margin',
            field=models.IntegerField(default=0, help_text='Sales margin as a percentage (non-negative).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='sales_price',
            field=models.IntegerField(default=0, help_text='Sales price must be non-negative.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
