# Generated by Django 5.1.4 on 2025-03-27 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0004_alter_totalsolutions_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalsolutions',
            name='buying_price_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last direct update to buying_price.', null=True),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='buying_price',
            field=models.FloatField(default=0.0, help_text='Buying price must be non-negative.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='list_price',
            field=models.FloatField(default=0.0, help_text='List price must be non-negative.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='totalsolutions',
            name='sales_price',
            field=models.FloatField(default=0.0, help_text='Sales price must be non-negative.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
