# Generated by Django 5.1.4 on 2025-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0005_totalsolutions_buying_price_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalsolutions',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
